version: "3.0"

services:
  db:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bookdb
      POSTGRES_PASSWORD: hans971!

    ports:
     - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge